<?php
$age =20;
        // if true first and second condition then print your right mesage....
            //logical and operator....
//if($age >= 18 && $age <= 21) {
         //logical or operator ..
        // if($age >= 18 || $age <=21) ..if true one conditon then print your true mesage....
        //  ! Not equal ..if condition is false then  print your true mesage....
    if($age >=15  xor $age <= 22){}
   if(!($age >= 18)){
    echo "you are eligible:";
} 
?>